sudo: false

language: python

python:
  - "3.5"
  - "3.6"

install: pip install tox-travis coveralls

script: tox

after_success: coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa5a289b7a0df8aefd68
  irc:
    channels:
      - "chat.freenode.net#asphalt"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
